title: Block, Dodge, Parry - SRD
description: The Systems Reference Document for Block, Dodge, Parry - an expansion to Cairn.
theme: just-the-docs

url: https://lars1808.github.io/Block-Dodge-Parry-SRD

aux_links:
  Template Repository: https://github.com/lars1808/Block-Dodge-Parry-SRD
