title: Block, Dodge, Parry - SRD
description: The Systems Reference Document for Block, Dodge, Parry - an expansion to Cairn.
theme: just-the-docs

url: https://lars1808.github.io/Block-Dodge-Parry-SRD

aux_links:
  Template Repository: https://github.com/lars1808/Block-Dodge-Parry-SRD
  
# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-EF30BZ876P
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

